/**
    Copyright (C) 2017 by jabelar

    This file is part of jabelar's Minecraft Forge modding examples; as such,
    you can redistribute it and/or modify it under the terms of the GNU
    General Public License as published by the Free Software Foundation,
    either version 3 of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    For a copy of the GNU General Public License see <http://www.gnu.org/licenses/>.
*/

package com.blogspot.jabelarminecraft.enchantmentglint.utilities;

import com.blogspot.jabelarminecraft.enchantmentglint.MainMod;

import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.item.Item;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

// TODO: Auto-generated Javadoc
/**
 * @author jabelar
 *
 */
public class Utilities
{
    
    /**
     * This allows you to add fancy formatting to the mod info displayed in the mod list.
     *
     * @param event the new mod info
     */
    public static void setModInfo(FMLPreInitializationEvent event)
    {
        // hard-code mod information so don't need mcmod.info file
        event.getModMetadata().autogenerated = false; // stops it from complaining about missing mcmod.info
        event.getModMetadata().name = Utilities.stringToRainbow(MainMod.MODNAME);
        event.getModMetadata().credits = MainMod.MODCREDITS;
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(TextFormatting.RED + MainMod.MODAUTHOR);
        event.getModMetadata().description = TextFormatting.YELLOW + MainMod.MODDESCRIPTION;
        event.getModMetadata().url = MainMod.MODURL;
        event.getModMetadata().logoFile = MainMod.MODLOGO;
    }

    // Need to call this on item instance prior to registering the item
    /**
     * Sets the item name.
     *
     * @param parItem the item
     * @param parItemName the item name
     * @return the item
     */
    // chainable
    public static Item setItemName(Item parItem, String parItemName)
    {
        parItem.setRegistryName(parItemName);
        parItem.setTranslationKey(parItemName);
        return parItem;
    }

    // Need to call this on block instance prior to registering the block
    /**
     * Sets the block name.
     *
     * @param parBlock the block
     * @param parBlockName the block name
     * @return the block
     */
    // chainable
    public static Block setBlockName(Block parBlock, String parBlockName)
    {
        parBlock.setRegistryName(parBlockName);
        parBlock.setTranslationKey(parBlockName);
        return parBlock;
    }

    /*
     * Text Utilities
     */

    /**
     * String to rainbow.
     *
     * @param parString the string
     * @param parReturnToBlack the return to black
     * @return the string
     */
    public static String stringToRainbow(String parString, boolean parReturnToBlack)
    {
        int stringLength = parString.length();
        if (stringLength < 1)
        {
            return "";
        }
        String outputString = "";
        TextFormatting[] colorChar = {
                TextFormatting.RED,
                TextFormatting.GOLD,
                TextFormatting.YELLOW,
                TextFormatting.GREEN,
                TextFormatting.AQUA,
                TextFormatting.DARK_AQUA,
                TextFormatting.LIGHT_PURPLE,
                TextFormatting.DARK_PURPLE
        };
        for (int i = 0; i < stringLength; i++)
        {
            outputString = outputString + colorChar[i % 8] + parString.substring(i, i + 1);
        }
        // return color to a common one after (most chat is white, but for other GUI might want black)
        if (parReturnToBlack)
        {
            return outputString + TextFormatting.BLACK;
        }
        return outputString + TextFormatting.WHITE;
    }

    /**
     * String to rainbow.
     *
     * @param parString the string
     * @return the string
     */
    // by default return to white (for chat formatting).
    public static String stringToRainbow(String parString)
    {
        return stringToRainbow(parString, false);
    }

    /**
     * String to golden.
     *
     * @param parString the string
     * @param parShineLocation the shine location
     * @param parReturnToBlack the return to black
     * @return the string
     */
    public static String stringToGolden(String parString, int parShineLocation, boolean parReturnToBlack)
    {
        int stringLength = parString.length();
        if (stringLength < 1)
        {
            return "";
        }
        String outputString = "";
        for (int i = 0; i < stringLength; i++)
        {
            if ((i + parShineLocation + Minecraft.getSystemTime() / 20) % 88 == 0)
            {
                outputString = outputString + TextFormatting.WHITE + parString.substring(i, i + 1);
            }
            else if ((i + parShineLocation + Minecraft.getSystemTime() / 20) % 88 == 1)
            {
                outputString = outputString + TextFormatting.YELLOW + parString.substring(i, i + 1);
            }
            else if ((i + parShineLocation + Minecraft.getSystemTime() / 20) % 88 == 87)
            {
                outputString = outputString + TextFormatting.YELLOW + parString.substring(i, i + 1);
            }
            else
            {
                outputString = outputString + TextFormatting.GOLD + parString.substring(i, i + 1);
            }
        }
        // return color to a common one after (most chat is white, but for other GUI might want black)
        if (parReturnToBlack)
        {
            return outputString + TextFormatting.BLACK;
        }
        return outputString + TextFormatting.WHITE;
    }

    /**
     * String to golden.
     *
     * @param parString the string
     * @param parShineLocation the shine location
     * @return the string
     */
    // by default return to white (for chat formatting).
    public static String stringToGolden(String parString, int parShineLocation)
    {
        return stringToGolden(parString, parShineLocation, false);
    }
}
